<?php include 'header.phtml' ?>
    <div class="row">
    <?php include 'sidebar.phtml' ?>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap
         flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Blogs</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                    <span data-feather="calendar"></span>
                    This week
                </button>
            </div>
        </div>

            <div class="col-12">
                <a class="btn btn-success" href="addBlog">Add Blog</a>
               
            </div>
        <div class="table-responsive">
        <form action="alterBlog" method="POST">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Title</th>
                            <th scope="col">Category</th>
                            <th scope="col">Description</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                            <?php if ($_SESSION['userData']['role'] == 'admin') {
                            echo '
                            <th scope="col">Permission</th>';
                            }
                            ?>
                            <th scope="col">View</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach ($data as $key => $value) {
                                echo "<tr>
                  <td>" . $value->id . "</td>
                  <td>" . $value->title . "</td>
                  <td>" . $value->category . "</td>
                  <td>" . $value->description . "</td>
                  <td>" . $value->status . "</td>
                  <td>
                    <a class = 'btn btn-primary' href='editBlog?id=" . $value->id . "'>Edit</a>
                    <button class = 'btn btn-danger' type='submit' name = 'deleteBlog' 
                    value = " . $value->id . ">Delete</button>
                  </td>";
                    if ($_SESSION['userData']['role'] == 'admin') {
                        if ($value->status == "Not Approved") {
                            echo "<td><button class='btn btn-success' 
                        type='submit' name = 'approve' value = " . $value->id . ">
                        Approve</button></td>

        ";
                        } else {
                        echo "<td><button class='btn btn-danger' 
                        type='submit' name = 'restrict' value = " . $value->id . ">
                        Restrict</button></td>
        ";
                        }
                            
                        }
                        
                        echo '</form>
                        <form action ="/frontend/singleBlog" method="POST">
                        <td> <button class="btn btn-warning"
                              type="submit" name = "singleBlog" value = ' . $value->id . '>
                              View
                        </button></td>
                        </form></tr>';
                    }

                        ?>
                    </tbody>
                </table>
            
            
        </div>
    </main>
    </div>
    </div>