<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
<?php if ($_SESSION['userData']['role']=='admin') {
?>
        <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/frontend/home">
              <span data-feather="home"></span>
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin/dashboard">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/allBlogs">
              <span data-feather="file"></span>
              Blogs
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin/allUsers">
              <span data-feather="users"></span>
              Users
            </a>
          </li>
        </ul>
        
<?php } elseif ($_SESSION['userData']['role']=='User') {
?>      
          <ul>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/frontend/home">
              <span data-feather="home"></span>
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin/dashboard">
              <span data-feather="home"></span>
              My Profile
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="allBlogs">
              <span data-feather="home"></span>
              My Blogs
            </a>
          </li>          
        </ul>

<?php } ?>

      </div>
    </nav>